// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef copy_usb_h
#define copy_usb_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Button.H>

class UserInterface {
private:
  Fl_Double_Window *m_window;
  Fl_Pack *m_pack;
  Fl_Button *m_btn_quit;
  inline void cb_m_btn_quit_i(Fl_Button*, void*);
  static void cb_m_btn_quit(Fl_Button*, void*);
  static void cb_watch_fd(int fd, void* v);
public:
  UserInterface(int argc, char** argv);
  void show();
  Fl_Progress *add_progress_bar(const char *name);
  void watch_fd(const char *name, int fd);
};
#endif
